_target_: limb.envs.launch.LaunchConfig
hz: 100.0

sensors:
  cameras:
    left_wrist_camera:
        _target_: limb.sensors.cameras.camera.CameraNode
        camera:
            _target_: limb.sensors.cameras.realsense_camera.RealsenseCamera
            serial_number: "409122274543"
    head_camera:
        _target_: limb.sensors.cameras.camera.CameraNode
        camera:
            _target_: limb.sensors.cameras.realsense_camera.RealsenseCamera
            serial_number: "215122256240"

robots:
  left: ["robot_configs/yam/left.yaml"]

agent:
  _target_: limb.agents.teleoperation.yam_gello_agent.YamGelloAgent
  host: "10.42.0.1"
  network_port: 5555
  bimanual: false
  left_motor_ids: [1, 2, 3, 4, 5, 6]
  joint_signs_left: [1, 1, -1, -1, -1, 1]
  joycon_gripper: true
  default_gripper_value: 0.0

station_metadata:
  world_frame: "left_arm"
